### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by joshaabraham** [czeckd/angular-svg-icon#59] opened 2018-11-15 22:29 UTC
Hi ! how are you ?

I am trying to apply your example and it appears that it's not working.
this is you example :
[svgStyle]="{'width.px':170,'fill':'rgb(150,50,255)','padding.px':1,'margin.px':3}"

this is how I use it : 
<svg-icon  [src]="imgSrc + icon" [svgStyle]="{'fill':'color'}"></svg-icon>

I get the shape of the svg, but cannot modifiy its color. 
How does that work exactly ? (I am on Angular 6)

regards .

**Comment by czeckd** [comment] 2018-11-17 06:15
It's hard to say without knowing what is in the svg that you're using. It may already have fill color set on it which may be causing a conflict.

What happens if you do this?
```html
<svg-icon [src]="imgSrc + icon" [svgStyle]="{ 'fill' : 'blue' }"></svg-icon>
```

Can you share the svg you're having difficulty with?

**Comment by nbora98** [comment] 2018-12-12 06:07
Hello,

https://www.iconfinder.com/icons/183586/computer_icon
I am using the svg icon from the above link and using it as below:

<svg-icon src="/images/station.svg" [svgStyle]="{'fill':'rgb(150,50,255)','width.px':64,'margin.px':25}"></svg-icon>

Width and margin gets applied but color is not working with this. Can you please help me for this?

Thanks in advance.

**Comment by czeckd** [comment] 2018-12-12 07:59
@nbora98 The problem is the svg. It needs to be prepared to work with styles as explained in the docs [SVG Preperation](https://github.com/czeckd/angular-svg-icon#svg-preparation).

This is how the svg is from the link:
```svg
<?xml version="1.0" ?>
<svg height="16px" version="1.1" viewBox="0 0 16 16" width="16px" xmlns="http://www.w3.org/2000/svg" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns:xlink="http://www.w3.org/1999/xlink">
<title/>
<defs/>
<g fill="none" fill-rule="evenodd" id="Icons with numbers" stroke="none" stroke-width="1">
<g fill="#000000" id="Group" transform="translate(-240.000000, -48.000000)">
<path d="M242.006845,49 L253.993155,49 C254.550051,49 255,49.4457352 255,49.9955775 L255,59.0044225 C255,59.555163 254.54922,60 253.993155,60 L250.5,60 L253,63 L243,63 L245.5,60 L242.006845,60 C241.449949,60 241,59.5542648 241,59.0044225 L241,49.9955775 C241,49.444837 241.45078,49 242.006845,49 Z M242,50 L242,59 L254,59 L254,50 Z M242,50" id="Rectangle 132"/>
</g>
</g>
</svg>
```

Specifically, you'll want to remove:

1. `height="16px"` and `width="16px"` attributes that override the size
2. `fill="#000000"` that is overriding the coloring
3. `<g fill="none" fill-rule="evenodd" id="Icons with numbers" stroke="none" stroke-width="1">` and the closing `</g>`

After those edits are done, the svg becomes:

```svg
<?xml version="1.0" ?>
<svg version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g id="Group" transform="translate(-240.000000, -48.000000)">
    <path d="M242.006845,49 L253.993155,49 C254.550051,49 255,49.4457352 255,49.9955775 L255,59.0044225 C255,59.555163 254.54922,60 253.993155,60 L250.5,60 L253,63 L243,63 L245.5,60 L242.006845,60
C241.449949,60 241,59.5542648 241,59.0044225 L241,49.9955775 C241,49.444837 241.45078,49 242.006845,49 Z M242,50 L242,59 L254,59 L254,50 Z M242,50" id="Rectangle 132"/>
  </g>
</svg>
```
This svg should now work with:

```html
<svg-icon src="/images/station.svg" [svgStyle]="{'fill':'rgb(150,50,255)','width.px':64,'margin.px':25}">
```

**Comment by nbora98** [comment] 2018-12-12 08:59
Hey,
Thanks a lot. Its working as expected.

**Comment by dweep119** [comment] 2019-09-17 08:20
Hey I am facing same issue here is my svg,

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><defs><style>.a,.b{fill:none;}.a{stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.5px;fill-rule:evenodd;}</style></defs><g transform="translate(2 4.9)"><g transform="translate(2 0.1)"><path class="a" d="M16.247,0H0L6.5,7.685V13l3.249,1.625V7.685Z"/></g><rect class="b" width="24" height="24" transform="translate(-2 -4.9)"/></g></svg>`

And Using like this,

`<svg-icon [applyCss]="true" src="assets/images/icon/filter.svg" class="multi-path-svg animated" [stretch]="false"
      [svgStyle]="{'width.px':175,'fill':'rgb(120,120,120)'}">
    </svg-icon>`

Thanks.

**Comment by czeckd** [comment] 2020-03-09 18:18
@dweep119 With `angular-svg-icon@9.1.0` this should work with that SVG:
```css
.filter {
    width: 175px;
    .a {
        fill: rgb(120,120,120);
    }
}
```
```html
<svg-icon src="assets/filter.svg" class="filter" viewBox="auto"></svg-icon>
```

![filt](https://user-images.githubusercontent.com/17859320/76244547-86868280-61f7-11ea-9cfb-9eabfdfd31bb.png)

**Closed as completed** 2020-03-11 06:07 UTC
