### ISSUE TITLE
Looks like [class] property doesn't work 

### ISSUE THREAD

**Issue by SiarheiBokuts** [czeckd/angular-svg-icon#111] opened 2020-10-20 14:53 UTC
i tried to use it like
`<svg-icon name='travel' [svgStyle]="{ 'width.px':22, 'height.px':22 }" [class]="'test-class'"></svg-icon>`

and i can't see test-class on the svg-icon compoent.
![image](https://user-images.githubusercontent.com/22210892/96603837-17c8e600-12fd-11eb-8862-fce1b13d58fd.png)

but with normal class like class="test-class" it works 

maybe it's because https://github.com/czeckd/angular-svg-icon/blob/4f6319ec165a293f387aa2a3c5d4632d7017dd01/projects/angular-svg-icon/src/lib/svg-icon.component.ts#L83

or i did something wrong?

**Comment by baxelson12** [comment] 2020-11-15 00:59
You need to use [applyClass]="true"
`<svg-icon src="assets/home.svg" [applyClass]="true" class="fill-current w-6 h-6 text-gray-300"></svg-icon>`

**Comment by Andikki** [comment] 2021-02-09 01:47
Simply putting `class` on `<svg-icon>` used to work in version 8.0.0, not in further versions.

Adding `[applyClass]="true"` doesn't quite work either - it puts the class on `<svg>` element, not the enclosing `<svg-icon>` element. In the end the effect is the same as using `svgClass` attribute. 

According to documentation, 

> [class] - An optional string of the class or classes to apply to the SVG (duplicates what is set on the svg-icon).
[applyClass] - An optional boolean (default is false) that works with [class] to duplicate the class attribute on the svg-icon and apply it to the SVG.
[svgClass] - An optional string of the class or classes to apply to the SVG (independent of what is set for the class on the svg-icon).

I'm not sure I quite understand it - what does "duplicates what is set on the svg-icon" mean and how does one set a class on svg-icon if `class` is not it?
Or is `class` supposed to be always applied to `<svg-icon>` and optionally to `<svg>` as well with `[applyClass]="true"`?

Anyway, currently there doesn't seem to be a way to set class to `<svg-icon>` element.

**Comment by czeckd** [comment] 2021-02-09 07:30
@Andikki - 

> Simply putting `class` on `<svg-icon>` used to work in version 8.0.0, not in further versions.
> […]
> Anyway, currently there doesn't seem to be a way to set class to `<svg-icon>` element.

Using `class` on `<svg-icon>` seems to work for me, I do not understand why you state it cannot be set. Consider this example template using angular-svg-icon@11.0.0 and Angular 11:

```html
<div>
</div>
<div>
    <svg-icon src="assets/images/moon-o.svg"></svg-icon>
</div>
<div>
    <svg-icon src="assets/images/moon-o.svg" class="onIcn"></svg-icon>
</div>
<div>
    <svg-icon src="assets/images/moon-o.svg" class="onIcn" [applyClass]="true"></svg-icon>
</div>
<div>
    <svg-icon src="assets/images/moon-o.svg" class="onIcn" svgClass="mySvg"></svg-icon>
</div>

<div>
    <svg-icon src="assets/images/moon-o.svg" svgClass="mySvg"></svg-icon>
</div>
```
With the following styles:
```css
div {
  height: 64px;
  width: 64px;
  border: 1px dashed gray;
  margin: 12px;
  fill: red;
}

.onIcn {
  fill: blue;
  height: 100%;
}

.mySvg {
  width: 48px;
  height: 48px;
}

svg.onIcn {
  fill: white;
  background-color: black;
  transform: rotateY(180deg);
}
```
This produces:
![example](https://user-images.githubusercontent.com/17859320/107327967-d8b4d100-6a62-11eb-8aaa-33b628053f6f.png)

With the corresponding generated mark-up (svg path removed for brevity):
```html
<app-root _nghost-jac-c18="" ng-version="11.1.2">
  <div _ngcontent-jac-c17=""></div>
  <div _ngcontent-jac-c17="">
    <svg-icon _ngcontent-jac-c17="" src="assets/images/moon-o.svg" ng-reflect-src="assets/images/moon-o.svg">
      <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" _ngcontent-jac-c17=""></svg>
    </svg-icon>
  </div>
  <div _ngcontent-jac-c17="">
    <svg-icon _ngcontent-jac-c17="" src="assets/images/moon-o.svg" class="onIcn" ng-reflect-src="assets/images/moon-o.svg">
      <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" _ngcontent-jac-c17=""></svg>
    </svg-icon>
  </div>
  <div _ngcontent-jac-c17="">
    <svg-icon _ngcontent-jac-c17="" src="assets/images/moon-o.svg" class="onIcn" ng-reflect-src="assets/images/moon-o.svg" ng-reflect-apply-class="true">
      <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" _ngcontent-jac-c17="" class="onIcn"></svg>
    </svg-icon>
  </div>
  <div _ngcontent-jac-c17="">
    <svg-icon _ngcontent-jac-c17="" src="assets/images/moon-o.svg" svgclass="mySvg" class="onIcn" ng-reflect-src="assets/images/moon-o.svg" ng-reflect-svg-class="mySvg">
      <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" _ngcontent-jac-c17="" class="mySvg"</svg>
    </svg-icon>
  </div>
  <div _ngcontent-jac-c17="">
    <svg-icon _ngcontent-jac-c17="" src="assets/images/moon-o.svg" svgclass="mySvg" ng-reflect-src="assets/images/moon-o.svg" ng-reflect-svg-class="mySvg">
      <svg viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg" _ngcontent-jac-c17="" class="mySvg"></svg>
    </svg-icon>
  </div>
</app-root>
```
* The first box is an empty `div`. 
* The second box is a `div` with the `svg-icon`.
* The third box is a `div` with the `svg-icon` set with `class="onIcn"`, which shows the `class` on `svg-icon` element. _This is what is not working for you?_
* The fourth box is a `div` with the `svg-icon` set with `class="onIcn"` and `[applyClass]="true"`, which has the `class` on `svg-icon` element and has the same `class`, `onIcn`, also on the `svg`. This causes an additional class to be activated, `svg.onIcn`, since the `onIcn` class is now on the `svg`.
* The fifth box is a `div` with with the `svg-icon` set with `class="onIcn"` and `svgClass="mySvg"`. The `onIcn` is on the `svg-icon` element and the`mySvg` is the class on the `svg`.
* The sixth box is a `div` with with the `svg-icon` set with only  `svgClass="mySvg"`. There is no `class` on the `svg-icon` element and the `svg` has the `mySvg` as its class.

So, it appears to me that `class` can be set on `svg-icon` by just using the `class` attribute. Can you provide an example of where this is not working for you please?

**Comment by Andikki** [comment] 2021-02-09 19:23
I see. The code where `class` broke uses interpolation, like so:
```
<svg-icon src="./assets/some-icon.svg" class="icon--{{someCalculatedValue}}"></svg-icon>
```
In this case, with `someCalculatedValue` resolving to `1`, I should see the class `icon--1` on the `<svg-icon>`, but it doesn't happen.

I now see that simple cases with no interpolation work as intended.

**Comment by czeckd** [comment] 2021-02-10 05:51
@Andikki - Thanks! That was the clue I needed. A new version should be available shortly that hopefully will resolve this interpolated `class` issue on `svg-icon`.

**Closed as completed** 2021-02-16 04:57 UTC
